
spring:
  application:
    name: novel
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database: mysql
    hibernate:
      ddl-auto: update

    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novel?serverTimezone=Asia/Seoul
    username: root
    password: wls960aha!
logging:
  level:
    org:
      springframework:
        security: DEBUG
file:
  path: /Users/ijinmo/Desktop/imgtest/
